/// <reference types="vitest" />
import { defineConfig, loadEnv, type ProxyOptions } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { visualizer } from 'rollup-plugin-visualizer'
import fs from 'fs'
import path from 'path'

type ProxyConfig = Record<string, ProxyOptions>

/**
 * Load HTTPS certificates for local development.
 * 
 * Certificates are generated by `scripts/setup-https.js` using mkcert.
 * If certificates don't exist, this returns undefined and HTTPS is skipped.
 */
function loadHttpsCerts(): { key: string; cert: string } | undefined {
  const certDir = path.resolve(__dirname, '.vite-certs')
  const certFile = path.join(certDir, 'localhost.crt')
  const keyFile = path.join(certDir, 'localhost.key')

  // Return undefined if certificates don't exist (HTTPS will be skipped)
  if (!fs.existsSync(certFile) || !fs.existsSync(keyFile)) {
    return undefined
  }

  return {
    cert: fs.readFileSync(certFile, 'utf-8'),
    key: fs.readFileSync(keyFile, 'utf-8'),
  }
}

function parseProxyTarget(env: Record<string, string>, envVar: string): ProxyOptions | null {
  const value = env[envVar]
  if (!value) return null
  try {
    return JSON.parse(value) as ProxyOptions
  } catch {
    return { target: value, changeOrigin: true }
  }
}

function buildProxyConfig(env: Record<string, string>): ProxyConfig {
  const proxyConfig: ProxyConfig = {}

  const apiTarget = parseProxyTarget(env, 'VITE_PROXY_API')
  if (apiTarget) proxyConfig['/api'] = apiTarget

  const wsTarget = parseProxyTarget(env, 'VITE_PROXY_WS')
  if (wsTarget) proxyConfig['/ws'] = wsTarget

  const prefix = 'VITE_PROXY_'
  for (const [key, value] of Object.entries(env)) {
    if (key.startsWith(prefix) && key !== 'VITE_PROXY_API' && key !== 'VITE_PROXY_WS') {
      const path = '/' + key.slice(prefix.length).toLowerCase().replace(/_/g, '/')
      try {
        proxyConfig[path] = JSON.parse(value) as ProxyOptions
      } catch {
        proxyConfig[path] = { target: value, changeOrigin: true }
      }
    }
  }

  if (Object.keys(proxyConfig).length === 0) {
    proxyConfig['/api'] = { target: env.VITE_API_URL || 'http://localhost:3000', changeOrigin: true }
    proxyConfig['/ws'] = { target: env.VITE_WS_URL || 'ws://localhost:3000', ws: true }
  }

  return proxyConfig
}

// Hostnames that are always a local/dev default, never a real third-party
// origin worth a preconnect/dns-prefetch hint (#509). Guards against emitting
// hints for `http://localhost:3000`-style fallbacks when VITE_API_URL /
// VITE_WS_URL aren't actually configured for this build.
const DEV_DEFAULT_HOSTS = new Set(['localhost', '127.0.0.1', '0.0.0.0', '::1'])

function isKnownProductionOrigin(rawUrl: string | undefined): string | null {
  if (!rawUrl) return null
  try {
    const url = new URL(rawUrl.replace(/^ws:/, 'http:').replace(/^wss:/, 'https:'))
    if (DEV_DEFAULT_HOSTS.has(url.hostname)) return null
    return url.origin
  } catch {
    return null
  }
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  const proxyConfig = buildProxyConfig(env)

  // Resource hints are only emitted for explicitly configured production
  // origins — not the localhost fallbacks used in local dev — so preview/dev
  // builds without real API/WS origins don't ship dead preconnect hints.
  const origins = new Set<string>()

  const apiOrigin = isKnownProductionOrigin(env.VITE_API_URL)
  if (apiOrigin) origins.add(apiOrigin)

  const wsOrigin = isKnownProductionOrigin(env.VITE_WS_URL)
  if (wsOrigin) origins.add(wsOrigin)

  const hints = Array.from(origins)
    .flatMap((origin) => [
      `<link rel="preconnect" href="${origin}" />`,
      `<link rel="dns-prefetch" href="${origin}" />`,
    ])
    .join('\n    ')

  return {
    plugins: [
      react(),
      tailwindcss(),
      {
        name: 'resource-hints',
        transformIndexHtml: {
          order: 'post',
          handler(html: string) {
            return hints ? html.replace('<!-- __RESOURCE_HINTS__ -->', hints) : html
          },
        },
      },
      {
        name: 'preload-critical-assets',
        transformIndexHtml: {
          order: 'post',
          handler(html: string) {
            const jsMatch = html.match(/<script\s+type="module"[^>]*src="([^"]+)"[^>]*><\/script>/)
            const cssMatch = html.match(/<link\s+rel="stylesheet"[^>]*href="((?!https?:\/\/)[^"]+)"[^>]*>/)

            const preloads: string[] = []

            if (cssMatch) {
              preloads.push(`<link rel="preload" as="style" href="${cssMatch[1]}" crossorigin />`)
            }

            if (jsMatch) {
              preloads.push(`<link rel="modulepreload" href="${jsMatch[1]}" crossorigin />`)
            }

            if (preloads.length === 0) return html

            return html.replace('</title>', `</title>\n    ${preloads.join('\n    ')}`)
          },
        },
      },
      ...(process.env.ANALYZE === 'true'
        ? [
            visualizer({
              filename: 'reports/bundle-analysis.html',
              open: false,
              gzipSize: true,
              brotliSize: true,
            }),
          ]
        : []),
    ],
    base: '/Stellar-Unified-Price-Oracle-Frontend-/',
    build: {
      // Generate hidden source maps (not inlined into JS — kept as separate .map files).
      // These are NOT uploaded to the CDN/static host; a post-build CI step strips them
      // from the deployment artifact and uploads them to the error-tracking service
      // (Sentry) instead.  See docs/source-maps.md for the full strategy.
      sourcemap: mode === 'production' ? 'hidden' : true,
      rollupOptions: {
        output: {
          entryFileNames: 'assets/[name]-[hash].js',
          chunkFileNames: 'assets/[name]-[hash].js',
          assetFileNames: 'assets/[name]-[hash][extname]',
          manualChunks(id) {
            const moduleId = id.replace(/\\/g, '/')

            if (moduleId.includes('/node_modules/')) {
              if (
                moduleId.includes('/react/') ||
                moduleId.includes('/react-dom/') ||
                moduleId.includes('/react-router') ||
                moduleId.includes('/scheduler/')
              ) {
                return 'vendor-react'
              }
              if (moduleId.includes('/@tanstack/react-virtual/')) {
                return 'vendor-tables'
              }
              if (
                moduleId.includes('/i18next/') ||
                moduleId.includes('/react-i18next/') ||
                moduleId.includes('/i18next-browser-languagedetector/')
              ) {
                return 'vendor-i18n'
              }
              if (moduleId.includes('/@tanstack/react-query/')) {
                return 'vendor-data'
              }
              if (moduleId.includes('/comlink/')) {
                return 'vendor-workers'
              }
              if (moduleId.includes('/@stellar/')) {
                return 'vendor-stellar'
              }
              if (moduleId.includes('/zod/')) {
                return 'vendor-validation'
              }
            }

            return undefined
          },
        },
      },
    },
    server: {
      port: 5173,
      proxy: proxyConfig,
      /**
       * Hot Module Replacement configuration for faster, more reliable development
       * 
       * Key optimizations:
       * 1. Direct protocol (ws/wss) instead of fallback to long-polling
       * 2. Shorter reconnect delays for faster feedback loops
       * 3. Full reload fallback when HMR fails (prevents stale state)
       * 4. Increased timeout to handle slow networks
       */
      hmr: {
        protocol: 'ws',
        host: 'localhost',
        port: 5173,
        timeout: 10_000,  // 10 seconds before full reload fallback
      },
      /**
       * HTTPS support for local development.
       * 
       * Service Workers, geolocation, and some WebSocket features require HTTPS.
       * Certificates are auto-generated by `scripts/setup-https.js` using mkcert.
       * 
       * Enable HTTPS:
       *   npm run dev:https
       *   HTTPS=true npm run dev
       *   VITE_HTTPS=true npm run dev
       * 
       * If certificates don't exist, HTTP is used (graceful fallback).
       */
      https: process.env.HTTPS === 'true' || process.env.VITE_HTTPS === 'true'
        ? loadHttpsCerts() || false
        : false,
    },
  }
})
