import { useState, type ReactElement } from 'react'
import { config } from '../config'
import { readJson, STORAGE_KEYS, writeJson } from '../utils/storage'

type Delivery = { at: number; status: number | 'failed'; latencyMs: number; reason?: string }
type Webhook = { id: string; url: string; events: string[]; enabled: boolean; createdAt: number; deliveries: Delivery[] }
const initial = (): Webhook[] => readJson<Webhook[]>(STORAGE_KEYS.developerWebhooks, [])

export function Webhooks(): ReactElement {
  const [hooks, setHooks] = useState<Webhook[]>(initial)
  const [url, setUrl] = useState('')
  const [events, setEvents] = useState('price_update')
  const [secret, setSecret] = useState('')
  const [status, setStatus] = useState<string | null>(null)
  const persist = (next: Webhook[]) => { setHooks(next); writeJson(STORAGE_KEYS.developerWebhooks, next) }
  const save = () => { try { const parsed = new URL(url); if (parsed.protocol !== 'https:') throw new Error('HTTPS is required'); const next = [...hooks, { id: crypto.randomUUID(), url, events: events.split(',').map((event) => event.trim()).filter(Boolean), enabled: true, createdAt: Date.now(), deliveries: [] }]; persist(next); setUrl(''); setSecret(''); setStatus('Webhook created. The signing secret is held only for this session.') } catch (error) { setStatus(error instanceof Error ? error.message : 'Enter a valid webhook URL') } }
  const test = async (hook: Webhook) => { const started = performance.now(); try { const response = await fetch(hook.url, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(secret ? { 'X-Webhook-Secret': secret } : {}) }, body: JSON.stringify({ type: 'price_update', test: true, timestamp: Date.now() }) }); const delivery = { at: Date.now(), status: response.status, latencyMs: Math.round(performance.now() - started), ...(response.ok ? {} : { reason: response.statusText || 'Request failed' }) }; persist(hooks.map((item) => item.id === hook.id ? { ...item, deliveries: [delivery, ...item.deliveries].slice(0, 10) } : item)); setStatus(response.ok ? 'Test event delivered.' : `Test event failed (${response.status}).`) } catch (error) { const delivery = { at: Date.now(), status: 'failed' as const, latencyMs: Math.round(performance.now() - started), reason: error instanceof Error ? error.message : 'Network error' }; persist(hooks.map((item) => item.id === hook.id ? { ...item, deliveries: [delivery, ...item.deliveries].slice(0, 10) } : item)); setStatus('Test event failed. Check the endpoint and CORS settings.') } }
  const rotate = () => { setSecret(crypto.randomUUID().replaceAll('-', '')); setStatus('New signing secret generated. Copy it now; it is not persisted.') }
  return <div className="max-w-4xl mx-auto space-y-6"><header><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Developer webhooks</h1><p className="text-sm text-gray-500 mt-1">Subscribe to price events and inspect delivery health.</p></header><section className="rounded-xl border border-gray-800 bg-gray-900/50 p-5 space-y-4"><h2 className="text-lg font-semibold text-white">Add endpoint</h2><input aria-label="Webhook URL" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/webhooks" className="w-full rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-white" /><input aria-label="Events" value={events} onChange={(event) => setEvents(event.target.value)} className="w-full rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-white" /><div className="flex gap-2"><button type="button" onClick={rotate} className="px-3 py-2 rounded-lg border border-gray-700 text-gray-300">Rotate secret</button><button type="button" onClick={save} className="px-3 py-2 rounded-lg bg-cyan-600 text-white">Create webhook</button></div>{secret && <code className="block break-all text-xs text-amber-300">Session secret: {secret}</code>}</section>{status && <p role="status" className="text-sm text-cyan-400">{status}</p>}<section className="space-y-3">{hooks.length === 0 && <p className="text-sm text-gray-500">No webhook subscriptions yet.</p>}{hooks.map((hook) => <article key={hook.id} className="rounded-xl border border-gray-800 bg-gray-900/50 p-5"><div className="flex items-center justify-between gap-3"><div><code className="text-sm text-gray-200">{hook.url}</code><p className="text-xs text-gray-500 mt-1">Events: {hook.events.join(', ')}</p></div><button type="button" onClick={() => persist(hooks.filter((item) => item.id !== hook.id))} className="text-xs text-red-400">Disable</button></div><div className="mt-4 flex items-center justify-between"><h3 className="text-sm font-medium text-gray-300">Recent deliveries</h3><button type="button" onClick={() => void test(hook)} className="px-3 py-1.5 rounded-lg border border-cyan-800 text-cyan-400 text-xs">Send test event</button></div>{hook.deliveries.length > 0 && <ul className="mt-2 space-y-1 text-xs text-gray-500">{hook.deliveries.map((delivery, index) => <li key={`${delivery.at}-${index}`}>{new Date(delivery.at).toLocaleString()} · {delivery.status} · {delivery.latencyMs}ms{delivery.reason ? ` · ${delivery.reason}` : ''}</li>)}</ul>}</article>)}</section><p className="text-xs text-gray-600">API base: {config.apiUrl}</p></div>
}
